apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: cw5x1cm35-nodejs
  janus-idp.io/tekton: cw5x1cm35-nodejs
  backstage.io/kubernetes-id: cw5x1cm35-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: cw5x1cm35-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
