apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: cw5x1cm35-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: cw5x1cm35-nodejs 
  name: cw5x1cm35-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: cw5x1cm35-nodejs 
